name: Build IOS
on: workflow_dispatch
jobs:
  iOS:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib git lime https://github.com/FunkinDroidTeam/lime.git --quiet
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp.git --quiet
          haxelib install openfl --quiet
          haxelib install format --quiet
          haxelib run lime rebuild hxcpp

      - name: Compile
        run: haxelib run lime build ios -nosign

      - name: Make .ipa
        run: |
          echo "$(ls)"
          cd export/
          echo "$(ls)"
          cd release/
          echo "$(ls)"
          cd ios/
          echo "$(ls)"
          cd build/
          echo "$(ls)"
          cd Debug-iphoneos
          echo "$(ls)"
          mkdir Payload
          mv *.app Payload
          zip -r LimeHelloWorld.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Debug-iphoneos/*.ipa
          if-no-files-found: error
